# Generated by Django 5.0 on 2024-02-13 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
            ],
            options={
                'verbose_name': 'Feiertag',
                'verbose_name_plural': 'Feiertage',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('starts_at', models.TimeField(verbose_name='Starts at')),
                ('ends_at', models.TimeField(verbose_name='Ends at')),
                ('title', models.CharField(default='', max_length=80, verbose_name='Title')),
                ('required_employees_min', models.IntegerField(default=0, verbose_name='Minimum required employees')),
                ('required_employees_max', models.IntegerField(default=0, verbose_name='Maximum required employees')),
            ],
            options={
                'verbose_name': 'Schicht',
                'verbose_name_plural': 'Schichten',
            },
        ),
        migrations.CreateModel(
            name='ShiftRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_registered_by', to=settings.AUTH_USER_MODEL)),
                ('registree', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_registree', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shift_planner.shift')),
            ],
            options={
                'verbose_name': 'Schichtanmeldung',
                'verbose_name_plural': 'Schichtanmeldungen',
            },
        ),
    ]
